[template]
src = "server.cfg.tmpl"
dest = "/opt/server/cfg/server.cfg"
keys = [
  "/_$SERVER_ID/config/hostname",
  "/_$SERVER_ID/config/rcon_password",
  "/_$SERVER_ID/config/sv_search_key",
  "/_$SERVER_ID/config/sv_password",
  "/_$SERVER_ID/config/sv_alltalk",
  "/_$SERVER_ID/config/sv_consistency",
  "/_$SERVER_ID/config/sv_contact",
  "/_$SERVER_ID/config/sv_voiceenable",
  "/_$SERVER_ID/config/sv_region",
  "/_$SERVER_ID/config/sv_log_onefile",
  "/_$SERVER_ID/config/sv_logbans",
  "/_$SERVER_ID/config/sv_lan",
  "/_$SERVER_ID/config/sv_pure",
  "/_$SERVER_ID/config/sv_cheats",
  "/_$SERVER_ID/config/sv_gametypes",
  "/_$SERVER_ID/config/sv_unlag",
  "/_$SERVER_ID/config/sv_maxunlag",
  "/_$SERVER_ID/config/sv_steamgroup",
  "/_$SERVER_ID/config/sv_steamgroup_exclusive",
  "/_$SERVER_ID/config/mp_disable_autokick",
  "/_$SERVER_ID/config/sv_allow_lobby_connect_only",
  "/_$SERVER_ID/config/sv_forcepreload",
  "/_$SERVER_ID/config/sv_pure_kick_clients"
]