#!/bin/bash
# @author bfosberry

ACTION_KEY="$1"
ACTION_VALUE="$2"
MAX_ATTEMPTS=30

if [ "$ACTION_KEY" == "start" ]; then
    set_info_value "status" "Starting"
    /etc/init.d/game_server start
    set_info_value "status" "Running"
elif [[ "$ACTION_KEY" == "stop" ]]; then
    set_info_value "status" "Stopping"
    /etc/init.d/game_server stop
    set_info_value "status" "Stopped"
fi
